
// Extract the value generated by a loop
fn main() {
    let mut counter = 0;
    let result = loop {
        counter += 1;
        if counter == 10 {
            break counter * 2;
        }
    };
    println!("The result is {}", result);
}


// While loop
fn main() {
    let mut number = 3;
    while number != 0  {
        println!("{}!", number);
        number = number - 1;
    }
    println!("LIFTOFF!!!");
}


// Looping through a collection with for 
// We should use iter over everything else whenever possible 
fn main() {
    let a = [10, 20, 30, 40, 50];
    for element in a.iter() {
        println!("the value is: {}", element);
    }
}